project(a_opengles)

list(APPEND AOPENGLES_LIBRARIES "${AOPENGLES_LIBRARY_PATH}/libEGL.so")
list(APPEND AOPENGLES_LIBRARIES "${AOPENGLES_LIBRARY_PATH}/libGLESv1_CM.so")
list(APPEND AOPENGLES_LIBRARIES "${AOPENGLES_LIBRARY_PATH}/libGLESv2.so")
list(APPEND AOPENGLES_LIBRARIES "${AOPENGLES_LIBRARY_PATH}/libandroid.so")


list(APPEND MODULES_DETECTED ${PROJECT_NAME})
set(MODULES_DETECTED ${MODULES_DETECTED} PARENT_SCOPE)

set(SRCS opengles.c vidisp.c)

if(STATIC)
    add_library(${PROJECT_NAME} OBJECT ${SRCS})
else()
    add_library(${PROJECT_NAME} MODULE ${SRCS})
endif()

target_include_directories(${PROJECT_NAME} PRIVATE ${AOPENGLES_INCLUDE_DIR})
target_link_libraries(${PROJECT_NAME} PRIVATE ${AOPENGLES_LIBRARIES})
